### PR TITLE
PDV-1176 Customize TS repo

### PR DESCRIPTION
**Pull request by doru2k6**

### CODE REVIEW

**Comment by doru2k6** [comment]
mvn deploy

**Comment by tradeshiftcicomponents** [comment]
Released snapshot artifacts to the maven repo: 3.3.4-SNAPSHOT

**Comment by doru2k6** [comment]
mvn deploy

**Comment by tradeshiftcicomponents** [comment]
Released snapshot artifacts to the maven repo: 3.3.4-SNAPSHOT

**Review by JesperTerkelsen — APPROVED** [review]

**Pull request merged**
